### PR TITLE
Fix memory overhead

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
I'll provide numbers soon and give a shout when it's ready to merge.

**Comment by Therzok** [comment]
Ok, so, running the whole thing in VS diagnostics:

100 times iteration on a 65*1000*1000 bytes, gc.collect after each run - worst case possible.

* Old version, peak usage 167mb, 14.03s runtime
cc_old_002

* Old version, but with memorystream initialization set - 145mb, 8.78s runtime.
cc_init_001

* New version as in this PR, 74mb peak memory, 5.75s runtime
cc_old_002

Without GCs:
* Old - 259mb memory usage, 17.26s runtime
* Old with init - 351mb peak, 13.34s runtime
* New version - 76mb peak, 7.06s runtime.

I'd definitely say this is an improvement. It also seems that the byte arrays get reused (rare collections), so this is a big +.

These numbers are just for crunching and not meant to mean anything. overall speed and memory usage should be improved by this PR. Marking as ready to merge.

cc @kjpou1

**Comment by Therzok** [comment]
Tests done with [this code](https://gist.github.com/Therzok/400622b0107bfbc21268). File created in cmd/powershell in the working directory of the application with `fsutil createnew myfile.txt 65000000`.

**Comment by Therzok** [comment]
Also tested them for integrity.

**Comment by Therzok** [comment]
Up for theoretical case from #295:

The asset stream is X bytes.

With the old version, there would be at least ... bytes allocated:
* X bytes for the asset stream.
* 1 + 2 + 4 + 8 + ... + Y, where Y=2^k, Y>X
* X bytes for the byte array.

With the init version:
* X bytes for the asset stream.
* X bytes for the memorystream.
* X bytes for the bytearray.

With the new version:
* X bytes for the asset stream.
* X bytes for the bytearray.

**Comment by Therzok** [comment]
Just a further note. It may be useful to abstract this into an internal extension method on `Stream`s, since I've found multiple instances copyto()/toarray() calls on streams.

**Comment by kjpou1** [comment]
Thanks Marius

**Pull request merged**
