### PR TITLE
Polyline tilemap test: Changed code for drawing rectangles, polygons, an...

### PR DESCRIPTION
**Pull request by charliekilian**
I've converted this to use CCDrawNode for everything but drawing ellipses. I just don't see an easy way to do that in CCDrawNode. Do you have an example of this that I can look at? It would be nice to do away with the TmxMapEllipse class in favor of a more generic draw method.

### CODE REVIEW

**Comment by rtabbara** [comment]
We'll look to add a DrawEllipse method within CCDrawNode. For now, you might like to take a look at the newly added <code>CCGeometryBatch</code> class as an alternative approach.

**Comment by kjpou1** [comment]
Hey Charlie

That is great!!  As Rami has said we will add a DrawEllipse method to the CCDrawNode.  It should not take that long and will add an issue for this.

**Comment by kjpou1** [comment]
@rtabbara I have added an issue for the Ellipse drawing.  If that is the only thing missing then I think this is ready to merge.  Let me know and I will hit the button.

**Comment by kjpou1** [comment]
I am going to go ahead and merge this as it only effects the tests and we can add the ellipse drawing when the issue https://github.com/mono/CocosSharp/issues/154 is taken care of.

@charliekilian Thanks for this great work!!!

**Pull request merged**
