### PR TITLE
Fix : Tield map assets located in sub folders cannot be load.

### PR DESCRIPTION
**Pull request by gdwneo**

### CODE REVIEW

**Comment by gdwneo** [comment]
First time to try to create pull request, thanks for Kenneth Pouncey's help.

**Comment by kjpou1** [comment]
Thanks @gdwneo.  It is kind of confusing at the beginning but great job.

**Comment by kjpou1** [comment]
Hey @gdwneo you should probably post this on the forum in the discussion you started on this.  Let them know that it was fixed and reference the PR.  Again thanks.

**Comment by gdwneo** [comment]
Got it, thanks for mentioning me.

**Comment by kjpou1** [comment]
@gdwneo this looks like it broke the tilemap tests could you take a look again and make sure that the change also works with our tests.

**Comment by gdwneo** [comment]
@kjpou1 because in the test solution the picture url in tmx file contains the subfolder but actually they are under the same folder, that tmx file cannot open in the tiled map editor. Btw today I found another issue is cannot load multiple assets in one tmx file, trying to fix that...

**Comment by gdwneo** [comment]
@kjpou1 sorry the root cause is the line 445 in CCTileMapInfo.cs is unneeded, remove it then everything works well.

**Pull request merged**
