### PR TITLE
Cc tile map polylines and shapes

### PR DESCRIPTION
**Pull request by charliekilian**
These changes to CCTileMapInfo add parsing of polylines, polygons, and ellipses. The Y coordinate is properly adjusted to match CocosSharp coordinates.

### CODE REVIEW

**Comment by rtabbara** [comment]
@charliekilian Thanks very much! Probably the quickest way to merge your PR will be to wait to use your tests to check out that your changes run fine for us.

**Comment by rtabbara** [comment]
Merged. Thanks! If you prefer, we can change the test class <code>Shape.cs</code> to use CCDrawNode. Otherwise, if you've already started work on it, then we'd be happy to merge that in as well.

**Comment by charliekilian** [comment]
I should have a chance to work on that tonight.

**Comment by charliekilian** [comment]
I've made some changes and issued a pull request for it, but I have a few questions before I would consider it completely ready to go. Specifically, I can't find an easy way to render an ellipse with CCDrawNode. Circles, yes, but not ellipses. Am I missing something? Barring that, do you have a suggestion for drawing ellipses that isn't calling CCDrawPrimitives?

I've changed the rendering of polygons, polylines, and rectangles to use CCDrawNode.

**Pull request merged**
